export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const FETCH_SERVICES_FAILED = "FETCH_SERVICES_FAILED";
export const SET_SERVICES = "SET_SERVICES";
export const SET_SELECTED_SERVICE = "SET_SELECTED_SERVICE";

export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const CREATE_APPOINTMENT_START = "CREATE_APPOINTMENT_START";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_APPOINTMENTS_START = "FETCH_APPOINTMENTS_START";
export const FETCH_APPOINTMENTS_SUCCESS = "FETCH_APPOINTMENTS_SUCCESS";
export const FETCH_APPOINTMENTS_FAIL = "FETCH_APPOINTMENTS_FAIL";